"""Add timestamp to Reaction model

Revision ID: a8c418d7bd6d
Revises: 0de5f6c8600f
Create Date: 2025-06-15 13:36:14.197723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c418d7bd6d'
down_revision = '0de5f6c8600f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
